FROM eclipse-temurin:21-jdk AS build

WORKDIR /app

# Copy and build
COPY . /app
RUN ./mvnw clean package

# Use slim runtime image
FROM eclipse-temurin:21-jre

WORKDIR /app

COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java","-jar","app.jar"]
