spring:
  application:
    name: InsuranceBankingPlatform
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/insurance_banking_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      schema-locations: classpath:database/schema.sql
      data-locations: classpath:database/data.sql
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION:3600}

server:
  port: ${SERVER_PORT:8080}

frontend:
  url: ${FRONTEND_URL:http://localhost:4200}

logging:
  charset:
    console: UTF-8
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
    com:
      example:
        insurancebanking: DEBUG